# Generated by Django 4.2.6 on 2024-02-28 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0002_job_feedback_application"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="salt",
        ),
        migrations.AddField(
            model_name="job",
            name="industry",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Retail"),
                    (2, "Construction, Repair and Maintenance Services"),
                    (3, "Personal Customer Services"),
                    (4, "Restaurants & Food Services"),
                    (5, "Hotel & Travel Accommodation"),
                    (6, "Others"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="remote",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "In-Person"), (2, "Hybrid"), (3, "Remote")], null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="requirement",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Foundation Degree"),
                    (2, "GCSE"),
                    (3, "Certificate of Higher Education"),
                    (4, "Bachelor's Degree"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="employer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Part-Time"), (2, "Temporary"), (3, "Volunteer")],
                null=True,
            ),
        ),
    ]
