# Generated by Django 4.2.6 on 2024-03-11 14:34

import application.models.models
import application.models.user_model
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0003_remove_user_salt_job_industry_job_remote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=application.models.models.job_directory_path,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=application.models.user_model.user_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "submitted"), (2, "success"), (3, "reject"), (4, "error")]
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="job",
            name="other",
            field=models.CharField(max_length=512),
        ),
    ]
